version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "6000:5000"
    environment:
      - NODE_ENV=production

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  dashboard:
    build: ./dashboard
    ports:
      - "8000:4000"
    depends_on:
      - backend
